---
language: python
python: "3.6"
sudo: false
addons:
  apt:
    packages:
    - python3-pip

install:
  - pip3 install ansible ansible-lint
  - ansible --version
  - printf '[defaults]\nroles_path=../' >ansible.cfg

before_script:
  - cd ../
  - mv ansible-role-resume-viewer theque5t.resume_viewer
  - cd theque5t.resume_viewer

script:
  - ansible-lint tests/test.yml
  - ansible-playbook -i localhost, --syntax-check tests/test.yml
  - echo | ansible-playbook -i localhost, tests/test.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
